Module 23.5 Practice Day 02/mamar_bank/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import UserRegistrationView, UserLoginView, UserLogoutView, UserBankAccountUpdateView, UserPasswordChangeView, UserProfileView

urlpatterns = [
path('register/', UserRegistrationView.as_view(), name='register'),
path('login/', UserLoginView.as_view(), name='login'),
path('profile/', UserProfileView.as_view(), name='profile'),
path('updateProfile/', UserBankAccountUpdateView.as_view(), name='updateProfile'),
path('password-change/', UserPasswordChangeView.as_view(), name='password'),
path('logout/', UserLogoutView.as_view(), name='logout'),
]

Module 23.5 Practice Day 02/mamar_bank/mamar_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='homepage'),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

Module 23.5 Practice Day 02/mamar_bank/transactions/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawMoneyView, TransactionReportView, LoanRequestView, PayLoanView, LoanListView, TransferView

urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("report/", TransactionReportView.as_view(), name="transaction_report"),
    path("loans/", LoanListView.as_view(), name="loan_list"),
    path("loan_request/", LoanRequestView.as_view(), name="loan_request"),
    path("loan/<int:pk>/", PayLoanView.as_view(), name="loan_pay"),
    path("transfer/", TransferView.as_view(), name="transfer"),
]

Module 23.5 Practice Day 02/mamar_bank/transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE
# Create your models here.
class Transaction(models.Model):
    account = models.ForeignKey(UserBankAccount, related_name='transactions', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits= 12, decimal_places=2)
    balance_after_transaction = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']

Module 23.5 Practice Day 02/mamar_bank/transactions/forms.py
from django import forms
from .models import Transaction

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type']

    # disabling transaction_type
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput() # user er theke hide kora thakbe

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance 
        return super().save()

class DepositeForm(TransactionForm):
    def clean_amount(self): # amount field ke filter korlm
        min_deposite_amount = 100
        amount = self.cleaned_data.get('amount') #user er fill up kota form theke amra amount field er balire ke niye ashlm
        if amount < min_deposite_amount:
            raise forms.ValidationError(f'Minimum deposit amount is {min_deposite_amount}$')
        return amount
    
class WithdrawForm(TransactionForm):
    def clean_amount(self): # amount field ke filter korlm
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance #1000
        amount = self.cleaned_data.get('amount') #user er fill up kota form theke amra amount field er balire ke niye ashlm
        if amount < min_withdraw_amount:
            raise forms.ValidationError(f'Minimum withdraw amount is {min_withdraw_amount}$')
        elif amount > max_withdraw_amount:
            raise forms.ValidationError(f'Maximum withdraw amount is {max_withdraw_amount}$')
        elif amount > balance: # amount = 5000, balance = 2000
            raise forms.ValidationError('Insufficient balance')
        return amount
    
class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        return amount
    
class TransferForm(forms.ModelForm):
    recipient_id = forms.IntegerField(label="Recipient_id", required=True)
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    class Meta:
        model = Transaction
        fields = ['recipient_id', 'amount']

Module 23.5 Practice Day 02/mamar_bank/transactions/views.py
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404, redirect
from django.core.mail import EmailMultiAlternatives
from accounts.models import UserBankAccount, BankStatus
from django.db.models import Sum
from django.urls import reverse_lazy
from datetime import datetime
from django.contrib import messages
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, View, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Transaction
from .forms import DepositeForm, WithdrawForm, LoanRequestForm, TransferForm
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID
# Create your views here.
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('transaction_report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title' : self.title,
        })
        return context
    
def send_transaction_mail(user, amount, subject, template, **kwargs):
    mail_subject = "Deposite Message"
    # message = render_to_string(template,{
    #     'user': user,
    #     'amount': amount,
    # })
    context = {
        'user': user,
        'amount': amount,
    }
    context.update(kwargs)
    message = render_to_string(template, context)
    send_mail = EmailMultiAlternatives(subject,'','nasrullah9867@gmail.com', to=[user.email])
    send_mail.attach_alternative(message, "text/html")
    send_mail.send()

class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositeForm
    title = 'Deposite'

    def get_initial(self): # user dekhar agei form fill up krlm
        initial = {'transaction_type': DEPOSIT}
        return initial
    
    def form_valid(self, form):
        account = self.request.user.account

        bank_status = BankStatus.objects.first()
        if bank_status and bank_status.is_bankrupt:
            messages.error(self.request, "Bank is currently bankrupt. Transactions are disabled.")
            return redirect('homepage')
        
        amount = form.cleaned_data.get('amount')
        account.balance += amount # user er kase ase 500 depositted 500 so current amount is 1000
        account.save(
            update_fields=['balance']
        )
        messages.success(self.request, f"{amount}$ was deposited to you account")
        # sending email to user when deposited
        send_transaction_mail(self.request.user, amount, "Deposite Message", "transactions/deposite_message.html")

        return super().form_valid(form)
    
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw'

    def get_initial(self): # user dekhar agei form fill up krlm
        initial = {'transaction_type': WITHDRAWAL}
        return initial
    
    def form_valid(self, form):
        account = self.request.user.account
        
        bank_status = BankStatus.objects.first()
        if bank_status and bank_status.is_bankrupt:
            messages.error(self.request, "Bank is currently bankrupt. Transactions are disabled.")
            return redirect('homepage')
        
        amount = form.cleaned_data.get('amount')
        account.balance -= amount # user er kase ase 500 WITHDRAWAL 500 so current amount is 0
        account.save(
            update_fields=['balance']
        )
        messages.success(self.request, f"Successfuly withdrawn {amount}$ from your account")
        send_transaction_mail(self.request.user, amount, "Withdrawl Message", "transactions/withdrawl_message.html")
        return super().form_valid(form)
    
class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = 'Request Loan'

    def get_initial(self): # user dekhar agei form fill up krlm
        initial = {'transaction_type': LOAN}
        return initial
    
    def form_valid(self, form):
        bank_status = BankStatus.objects.first()
        if bank_status and bank_status.is_bankrupt:
            messages.error(self.request, "Bank is currently bankrupt. Transactions are disabled.")
            return redirect('homepage')
        
        amount = form.cleaned_data.get('amount')
        current_loan_count = Transaction.objects.filter(account = self.request.user.account, transaction_type=3, loan_approve = True).count()
        if current_loan_count >= 3:
            return HttpResponse("Loan request crossed limits")
        messages.success(self.request, f"Successfuly loan request sent about only {amount}$")
        send_transaction_mail(self.request.user, amount, "Loan Request Message", "transactions/loan_request_message.html")
        return super().form_valid(form)
    
class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction
    balance = 0 # filter korar pore ba age amar total balance ke show korbe
    context_object_name = "transactions_report"

    def get_queryset(self):
        # jodi user filter na kre
        queryset = super().get_queryset().filter(account=self.request.user.account)
        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

         # jodi user date filer kre
        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
            queryset = queryset.filter(timestamp__date__range=(start_date, end_date))

            self.balance = Transaction.objects.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance
        return queryset.distinct()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account
        })
        return context

class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, pk):
        loan = get_object_or_404(Transaction, pk=pk)

        if loan.loan_approve:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()

                send_transaction_mail(self.request.user, loan.amount, "Loan Payment Message", "transactions/loan_pay_message.html")

                return redirect('loan_list')
            else:
                messages.error(request, "Insufficient balance for loan payment")
                return redirect('loan_list')

class LoanListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "transactions/loan_request.html"
    context_object_name = "loans"

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = Transaction.objects.filter(account = user_account, transaction_type = LOAN)
        return queryset
    
class TransferView(LoginRequiredMixin, FormView):
    template_name = 'transactions/transfer_form.html'
    form_class = TransferForm
    success_url = reverse_lazy('transaction_report')
    
    def form_valid(self, form):
        from_account = self.request.user.account

        bank_status = BankStatus.objects.first()
        if bank_status and bank_status.is_bankrupt:
            messages.error(self.request, "Bank is currently bankrupt. Transactions are disabled.")
            return redirect('homepage')
        
        
        amount = form.cleaned_data.get('amount')
        recipient_account_no = form.cleaned_data.get('recipient_id')

        try:
            recipient_account = UserBankAccount.objects.get(account_no=recipient_account_no)
        except UserBankAccount.DoesNotExist:
            messages.error(self.request, f"Account with ID '{recipient_account_no}' not found.")
            return redirect('transfer')
        
        if from_account.balance >= amount:
            from_account.balance -= amount
            from_account.save()

            Transaction.objects.create(
                account = from_account,
                amount = amount,
                transaction_type = 5,
                balance_after_transaction = from_account.balance,
            )
            recipient_account.balance += amount
            recipient_account.save()
            Transaction.objects.create(
                account = recipient_account,
                amount = amount,
                transaction_type = 5,
                balance_after_transaction = recipient_account.balance,
            )
            messages.success(self.request, f"Transferred {amount}$ to account {recipient_account.account_no}")
            # sending email to both user when money sent
            send_transaction_mail(
                from_account.user, 
                amount, 'Send Money', 
                'transactions/send_money.html',to_username=recipient_account.user.username)
            
            send_transaction_mail(
                recipient_account.user,
                amount,
                'Money Received',
                'transactions/receive_money.html',
                to_email=recipient_account.user.email,
                from_username=from_account.user.username
            )
        else:
            messages.error(self.request, "Insufficient balance.")
        return redirect(self.success_url)
    

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/deposite_message.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>

<p>Your Deposite request for {{amount}} has been succefull. After Deposite your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/loan_approve_message.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>
<h2>Congratulations!! Your Loan Request for {{amount}}tk has been Approved</h2>
<p>After Loan Payment your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/loan_pay_message.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>

<p>Your Loan Payment request for {{amount}} has been succefull. After Loan Payment your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block body %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "loan_pay" loan.pk %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/loan_request_message.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>

<p>Your Loan request for {{amount}} has been succefull. After your Loan approval you will get the loan.</p>

<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/receive_money.html
<p>Hello {{ user.first_name }} {{ user.last_name }}</p>
<h2>Congratulations!! You have received {{ amount }} tk from {{ from_username }}.</h2>
<p>Your new balance is {{ user.account.balance }}</p>
<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/send_money.html
<p>Hello {{ user.first_name }} {{ user.last_name }}</p>
<h2>Congratulations!! Successfully Sent {{ amount }} tk to {{ to_username }}.</h2>
<p>After Sending Money, your total amount is {{ user.account.balance }}</p>

<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block body %}
<div class="flex flex-col items-center justify-center w-full h-full">
    <div class="w-full flex mt-5 justify-center -z-50 relative">
        <div class="bg-white w-5/12 rounded-lg">
            {% if title == 'Request Loan' %}
                <div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
            {% endif %}
            
            <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
            <form method="post" class="px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
    
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                        Amount
                    </label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
                </div>
                {% if form.amount.errors %} 
                {% for error in form.amount.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} 
                {% endif %}
                <div class="flex w-full justify-center">
                    <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                    Submit
                </button>
                </div>
            </form>
        </div>
        
    </div>
</div>
{% endblock %}

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/transaction_report.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block head_title %} Transaction Report{% endblock %}
{% block body %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2">
        <label for="start_date">From:&nbsp;</label>
        <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" type="date" id="start_date" name="start_date" />
      </div>
      <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12">
        <label for="end_date">To:&nbsp;</label>
        <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" type="date" id="end_date" name="end_date" />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
          Filter
        </button>
      </div>
    </div>
  </form>
  <table class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500">
    <thead class="bg-purple-900 text-white text-left">
      <tr class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold">
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions_report %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}">
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/transfer_form.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Transaction Form{% endblock %}
{% block body %}
<div class="flex flex-col items-center justify-center w-full h-full">
    <div class="w-full flex mt-5 justify-center -z-50 relative">
        <div class="bg-white w-5/12 rounded-lg">
            <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
            <form method="post" class="px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
                
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                        Amount
                    </label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
                    {% if form.amount.errors %} 
                        {% for error in form.amount.errors %}
                            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                        {% endfor %} 
                    {% endif %}
                </div>
                
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="recipient_id">
                        Recipient Account Number
                    </label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="recipient_id" id="recipient_id" type="number" required placeholder="Recipient Account Number">
                    {% if form.recipient_id.errors %} 
                        {% for error in form.recipient_id.errors %}
                            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                        {% endfor %} 
                    {% endif %}
                </div>

                <div class="flex w-full justify-center">
                    <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                        Transfer
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Module 23.5 Practice Day 02/mamar_bank/transactions/templates/transactions/withdrawl_message.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>

<p>Your Withdrawl request for {{amount}} has been succefull. After Withdrawl your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us!</p>
<p>Mamar Bank</p>